# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/admin/Documents/autonomous-vehicle/Zybo-Z7/AutonomousVehicle.xdc

# Block Designs: bd/Zynq_PS/Zynq_PS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_PS || ORIG_REF_NAME==Zynq_PS} -quiet] -quiet

# IP: bd/Zynq_PS/ip/Zynq_PS_processing_system7_0_0/Zynq_PS_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_PS_processing_system7_0_0 || ORIG_REF_NAME==Zynq_PS_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_PS/ip/Zynq_PS_axi_gpio_0_0/Zynq_PS_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_PS_axi_gpio_0_0 || ORIG_REF_NAME==Zynq_PS_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Zynq_PS/ip/Zynq_PS_axi_smc_0/Zynq_PS_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_PS_axi_smc_0 || ORIG_REF_NAME==Zynq_PS_axi_smc_0} -quiet] -quiet

# IP: bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_PS_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zynq_PS_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/admin/Documents/autonomous-vehicle/Zybo-Z7/AutonomousVehicle.gen/sources_1/bd/Zynq_PS/Zynq_PS_ooc.xdc
