domain_path: C:\Users\admin\Documents\autonomous-vehicle\Zybo-Z7\Vitis\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\ProgramFiles\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
