domain_path: C:\Users\admin\Documents\autonomous-vehicle\Zybo-Z7\Vitis\platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\ProgramFiles\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
