# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/admin/Documents/autonomous-vehicle/Zybo-Z7/AutonomousVehicle.srcs/sources_1/bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0.xci
# IP: The module: 'Zynq_PS_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Documents/autonomous-vehicle/Zybo-Z7/AutonomousVehicle.gen/sources_1/bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_PS_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/admin/Documents/autonomous-vehicle/Zybo-Z7/AutonomousVehicle.gen/sources_1/bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_PS_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/admin/Documents/autonomous-vehicle/Zybo-Z7/AutonomousVehicle.srcs/sources_1/bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0.xci
# IP: The module: 'Zynq_PS_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Documents/autonomous-vehicle/Zybo-Z7/AutonomousVehicle.gen/sources_1/bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_PS_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/admin/Documents/autonomous-vehicle/Zybo-Z7/AutonomousVehicle.gen/sources_1/bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_PS_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
